//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextExtractorConsoleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextExtractorConsoleApp.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title: 
        ///[{0}]
        ///Textbook content: 
        ///[{1}].
        /// </summary>
        internal static string ChapterTemplate {
            get {
                return ResourceManager.GetString("ChapterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;generate test&gt;
        ///Test should be more about topic than on content. It should check users&apos; understanding of material, nt their readin abilities. 
        ///Should contain:
        ///- Multiple-choice questions: 5
        ///- True-or-false questions: 2
        ///- Short answer questions: 2
        ///- One essay question
        ///Provide correct answers for each multiple-choice and true-or-false question. Each answer should be provided between &lt;&gt; angular brackets. DO NOT write any additional text at the answer, only &lt;answer&gt; between brackets right after each ques [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateTestsPrompt {
            get {
                return ResourceManager.GetString("GenerateTestsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a generator of learning materials.
        ///
        ///Generate a detailed and informative text about [User-Specified Topic]. 
        ///You will be provided with a content from the textbook or other resource. You should rephrase and simplify the content if it is possible.
        ///The content should cover the following aspects:
        ///- Overview of the topic
        ///- Key concepts and terminology
        ///- Important theories and models (if applicable)
        ///- Practical applications (if applicable)
        ///- Case studies or examples (if applicable)
        ///Ensure the con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemPrompt {
            get {
                return ResourceManager.GetString("SystemPrompt", resourceCulture);
            }
        }
    }
}
